# Generated by Django 4.0.3 on 2022-03-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ManyToManyField(to='books.topic'),
        ),
    ]
