# Generated by Django 4.0.3 on 2022-03-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='topic',
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.topic'),
        ),
    ]
