# Generated by Django 4.0.3 on 2022-03-09 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_topic_book_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
